version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: lunia_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env  # Backend'in kendi .env dosyası
    restart: always     # unless-stopped yerine always kullanmak sunucu restart attığında kesin kalkmasını sağlar
    networks:
      - lunia_network

  frontend:
    build: 
      context: ./frontend
    container_name: lunia_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env  # Frontend'in kendi .env dosyası
    depends_on:
      - backend          # Önce backend ayağa kalksın
    restart: always
    networks:
      - lunia_network

networks:
  lunia_network:
    driver: bridge       # İki konteynerin güvenli şekilde haberleşmesini sağlar